version: '3.8'

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_DATABASE: lang_rush

volumes:
  mongo_data: